name: Build smolBSD image

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
  workflow_dispatch:
    inputs:
      img:
        description: "Image target"
        required: true
        default: "rescue"
      arch:
        description: "Architecture"
        required: true
        default: "amd64"
      service:
        description: "Service to build on top of image"
        required: false
        default:
      mountro:
        description: "Build as read-only (y or empty)"
        required: false
        default:
      curlsh:
        description: "URL to a script to execute as finalizer"
        required: false
        default:

jobs:
  build_img:
    runs-on: ubuntu-latest
    container:
      image: debian:latest
      options: --privileged
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up environment
        run: |
          apt update && apt install -y curl xz-utils make sudo git libarchive-tools rsync
          rm -rf /var/cache

      - name: Build image
        run: |
          make SERVICE=${{ inputs.service }} NOSVCIMGBUILD=yes CURLSH=${{ inputs.curlsh }} ARCH=${{ inputs.arch || 'amd64' }} MOUNTRO=${{ inputs.mountro }} ${{ inputs.img || 'rescue' }}

      - uses: actions/upload-artifact@v4
        with:
          name: image
          path: "*.img"
